on: [push]

jobs:
  ai-robots-txt:
    runs-on: ubuntu-latest
    name: ai-robots-txt
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: |
          git rm robots.txt
          php -f code/action.php
          git config --global user.name "GitHub Action"
          git config --global user.email "github-action@neatnik.net"
          git add -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push
        shell: bash
